version: "3.9"
services:
  livekit:
    image: livekit/livekit-server:latest
    command: ["--dev"]
    env_file:
      - .env
    environment:
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"
    ports:
      - "7880:7880/tcp"
      - "7881:7881/tcp"
      - "7882:7882/udp"
